package is.interpreter;

public enum Symbols {
    CREATE,REMOVE,MOVE,MOVEOFF,SCALE,LIST,ALL,GROUPS,GROUP,UNGROUP,AREA,PERIMETER,CIRCLE,RECTANGLE,IMG,OPEN_BRACKET,CLOSE_BRACKET,COMMA,EOF,INVALID,ID,QUOTE,NUMBER
}
